### ISSUE TITLE
OpenStack content problems

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang-content#276]
Uma from CSA team is trying to create a new content for OpenStack , an operation named : 
“Get Openstack containers” (uses swift)
And she get's 500 error when using API from CloudSlang, issue might be that : 
Content-Type param is : text/plain

but it should be :

text/json

even that she added an input param for that...

**Comment by meirwah** [comment]
op code:

namespace: io.cloudslang.openstack

operation:
  name: get_openstack_containers
  inputs:
    - host
    - object_port:
        default: "'8080'"
    - token
    - tenant
    - proxy_host:
        required: false
    - proxy_port:
        required: false
    - proxyHost: "proxy_host if proxy_host else ''"
    - proxyPort: "proxy_port if proxy_port else ''"
    - headers:
        default: "'X-AUTH-TOKEN:' + token"
        overridable: false
    - url:
        default: "'http://'+ host + ':' + object_port + '/v1/' + 'AUTH_' + tenant + '?format=json'"
        overridable: false
    - method:
        default: "'get'"
        overridable: false
  action:
    java_action:
      className: io.cloudslang.content.httpclient.HttpClientAction
      methodName: execute
  outputs:
    - return_result: returnResult
    - status_code: statusCode
    - error_message: returnResult if statusCode != '202' else ''
  results:
    - SUCCESS : "'statusCode' in locals() and statusCode == '200'"
    - FAILURE

**Comment by meirwah** [comment]
log:

2015-08-03 14:37:32:930 2148093 [1_WorkerExecutionThread-11_101600078] INFO  io.cloudslang.lang.cli.SlangCLI  - Event received: EVENT_INPUT_START Data is: {EXECUTION_ID=101600078, PATH=0, DESCRIPTION=Pre Input binding for operation/flow, TIMESTAMP=Mon Aug 03 14:37:32 IST 2015, STEP_TYPE=EXECUTABLE, INPUTS=[host, object_port, token, tenant, proxy_host, proxy_port, proxyHost, proxyPort, headers, url, method], STEP_NAME=get_openstack_containers, TYPE=EVENT_INPUT_START}
2015-08-03 14:37:32:931 2148094 [1_WorkerExecutionThread-11_101600078] INFO  io.cloudslang.lang.cli.SlangCLI  - Event received: EVENT_INPUT_END Data is: {EXECUTION_ID=101600078, PATH=0, BOUND_INPUTS={proxy_port=null, proxyPort=, headers=X-AUTH-TOKEN:6ec0edec694c4b009af1816c1bfaa68f, method=get, proxy_host=null, host=16.77.19.30, object_port=8080, proxyHost=, tenant=bd9b98f6dafb4ceb8f3e79b05116a1e1, url=http://16.77.19.30:8080/v1/AUTH_bd9b98f6dafb4ceb8f3e79b05116a1e1?format=json, token=6ec0edec694c4b009af1816c1bfaa68f}, DESCRIPTION=Post Input binding for operation/flow, TIMESTAMP=Mon Aug 03 14:37:32 IST 2015, STEP_TYPE=EXECUTABLE, STEP_NAME=get_openstack_containers, TYPE=EVENT_INPUT_END}
2015-08-03 14:37:34:038 2149201 [1_WorkerExecutionThread-11_101600078] INFO  io.cloudslang.lang.cli.SlangCLI  - Event received: EVENT_ACTION_START Data is: {EXECUTION_ID=101600078, PATH=0, DESCRIPTION=Preparing to run action JAVA, TIMESTAMP=Mon Aug 03 14:37:32 IST 2015, STEP_TYPE=ACTION, STEP_NAME=null, TYPE=EVENT_ACTION_START, CALL_ARGUMENTS={proxy_port=null, proxyPort=, headers=X-AUTH-TOKEN:6ec0edec694c4b009af1816c1bfaa68f, method=get, proxy_host=null, host=16.77.19.30, object_port=8080, proxyHost=, tenant=bd9b98f6dafb4ceb8f3e79b05116a1e1, url=http://16.77.19.30:8080/v1/AUTH_bd9b98f6dafb4ceb8f3e79b05116a1e1?format=json, token=6ec0edec694c4b009af1816c1bfaa68f}}
2015-08-03 14:37:34:039 2149202 [1_WorkerExecutionThread-11_101600078] INFO  io.cloudslang.lang.cli.SlangCLI  - Event received: EVENT_ACTION_END Data is: {EXECUTION_ID=101600078, PATH=0, DESCRIPTION=Action performed, TIMESTAMP=Mon Aug 03 14:37:34 IST 2015, RETURN_VALUES={returnCode=0, responseHeaders=Content-Length: 17
Content-Type: text/plain
X-Trans-Id: tx4c483e61026647d6b1513-0055bf2fa7
Date: Mon, 03 Aug 2015 09:08:55 GMT
Connection: keep-alive, returnResult=An error occurred, reasonPhrase=Internal Error, finalLocation=http://16.77.19.30:8080/v1/AUTH_bd9b98f6dafb4ceb8f3e79b05116a1e1?format=json, protocolVersion=HTTP/1.1, statusCode=500}, STEP_TYPE=ACTION, STEP_NAME=null, TYPE=EVENT_ACTION_END}
2015-08-03 14:37:34:090 2149253 [1_WorkerExecutionThread-11_101600078] INFO  io.cloudslang.lang.cli.SlangCLI  - Event received: EVENT_OUTPUT_START Data is: {EXECUTION_ID=101600078, PATH=0, DESCRIPTION=Output binding started, executableResults=[io.cloudslang.lang.entities.bindings.Result@b4c99c[name=SUCCESS,expression='statusCode' in locals() and statusCode == '200'], io.cloudslang.lang.entities.bindings.Result@d4983f[name=FAILURE,expression=<null>]], TIMESTAMP=Mon Aug 03 14:37:34 IST 2015, executableOutputs=[io.cloudslang.lang.entities.bindings.Output@7ac7ee[name=return_result,expression=returnResult], io.cloudslang.lang.entities.bindings.Output@18baddc[name=status_code,expression=statusCode], io.cloudslang.lang.entities.bindings.Output@14566d8[name=error_message,expression=returnResult if statusCode != '202' else '']], STEP_TYPE=EXECUTABLE, actionReturnValues=ReturnValues{result='null', outputs={returnCode=0, responseHeaders=Content-Length: 17
Content-Type: text/plain
X-Trans-Id: tx4c483e61026647d6b1513-0055bf2fa7
Date: Mon, 03 Aug 2015 09:08:55 GMT
Connection: keep-alive, returnResult=An error occurred, reasonPhrase=Internal Error, finalLocation=http://16.77.19.30:8080/v1/AUTH_bd9b98f6dafb4ceb8f3e79b05116a1e1?format=json, protocolVersion=HTTP/1.1, statusCode=500}}, STEP_NAME=get_openstack_containers, TYPE=EVENT_OUTPUT_START}
2015-08-03 14:37:34:091 2149254 [1_WorkerExecutionThread-11_101600078] INFO  io.cloudslang.lang.cli.SlangCLI  - Event received: EVENT_OUTPUT_END Data is: {EXECUTION_ID=101600078, PATH=0, DESCRIPTION=Output binding finished, TIMESTAMP=Mon Aug 03 14:37:34 IST 2015, STEP_TYPE=EXECUTABLE, STEP_NAME=get_openstack_containers, TYPE=EVENT_OUTPUT_END, RESULT=FAILURE, OUTPUTS={return_result=An error occurred, status_code=500, error_message=An error occurred}}
2015-08-03 14:37:34:094 2149257 [1_WorkerExecutionThread-11_101600078] INFO  io.cloudslang.lang.cli.SlangCLI  - Event received: EVENT_EXECUTION_FINISHED Data is: {EXECUTION_ID=101600078, PATH=0, DESCRIPTION=Execution finished running, TIMESTAMP=Mon Aug 03 14:37:34 IST 2015, STEP_TYPE=EXECUTABLE, STEP_NAME=get_openstack_containers, TYPE=EVENT_EXECUTION_FINISHED, RESULT=FAILURE, OUTPUTS={return_result=An error occurred, status_code=500, error_message=An error occurred}}
2015-08-03 14:37:34:118 2149281 [scoreWorkerScheduler-1] INFO  io.cloudslang.lang.cli.SlangCLI  - Event received: SCORE_FINISHED_EVENT Data is: {IS_BRANCH=false, executionIdContext=101600078, systemContext=io.cloudslang.score.lang.SystemContext@a3f8bc52, EXECUTION_CONTEXT={userInputs={}, runEnv=io.cloudslang.lang.runtime.env.RunEnvironment@10b9177}}

**Comment by umavanth** [comment]
Thanks Meir for raising the issue

**Comment by orius123** [comment]
shouldn't content type be a header?

**Comment by orius123** [comment]
can you try and add an operation input:
```yaml
- contentType:
        default: "'text/json'"
```

**Comment by umavanth** [comment]
Yes added, but still the same issue

**Comment by umavanth** [comment]
I have tried for Cinder service- List Volumes, it is working fine, only for swift service getting 500 error

**Comment by orius123** [comment]
can you share the equivalent working curl command?

**Comment by umavanth** [comment]
i tried thru rest client:
http://16.77.19.30:8080/v1/AUTH_bd9b98f6dafb4ceb8f3e79b05116a1e1?format=json
X-Auth-Token: fc91fd35981d4a41b12a90b5594bfc37

**Comment by meirwah** [comment]
it possible that this:
```yaml
- contentType:
        default: "'text/json'"
```
does not work, because in the logs it seemed that the value is still "text/plain"

**Comment by orius123** [comment]
what logs?

**Comment by umavanth** [comment]
2015-08-03 18:20:09:762 15504925 [1_WorkerExecutionThread-11_101600218] INFO  io.cloudslang.lang.cli.SlangCLI  - Event received: EVENT_INPUT_START Data is: {EXECUTION_ID=101600218, PATH=0, DESCRIPTION=Pre Input binding for operation/flow, TIMESTAMP=Mon Aug 03 18:20:09 IST 2015, STEP_TYPE=EXECUTABLE, INPUTS=[host, object_port, token, tenant, proxy_host, proxy_port, proxyHost, proxyPort, headers, url, method, contentType], STEP_NAME=get_openstack_containers, TYPE=EVENT_INPUT_START}
2015-08-03 18:20:09:762 15504925 [1_WorkerExecutionThread-11_101600218] INFO  io.cloudslang.lang.cli.SlangCLI  - Event received: EVENT_INPUT_END Data is: {EXECUTION_ID=101600218, PATH=0, BOUND_INPUTS={proxy_port=null, proxyPort=, headers=X-AUTH-TOKEN:a1ae1713894f44a38f298df7815f6e5f, method=get, proxy_host=null, host=16.77.19.30, object_port=8080, proxyHost=, contentType=application/json, tenant=bd9b98f6dafb4ceb8f3e79b05116a1e1, url=http://16.77.19.30:8080/v1/AUTH_bd9b98f6dafb4ceb8f3e79b05116a1e1?format=json, token=a1ae1713894f44a38f298df7815f6e5f}, DESCRIPTION=Post Input binding for operation/flow, TIMESTAMP=Mon Aug 03 18:20:09 IST 2015, STEP_TYPE=EXECUTABLE, STEP_NAME=get_openstack_containers, TYPE=EVENT_INPUT_END}
2015-08-03 18:20:11:182 15506345 [1_WorkerExecutionThread-11_101600218] INFO  io.cloudslang.lang.cli.SlangCLI  - Event received: EVENT_ACTION_START Data is: {EXECUTION_ID=101600218, PATH=0, DESCRIPTION=Preparing to run action JAVA, TIMESTAMP=Mon Aug 03 18:20:09 IST 2015, STEP_TYPE=ACTION, STEP_NAME=null, TYPE=EVENT_ACTION_START, CALL_ARGUMENTS={proxy_port=null, headers=X-AUTH-TOKEN:a1ae1713894f44a38f298df7815f6e5f, method=get, proxyHost=, url=http://16.77.19.30:8080/v1/AUTH_bd9b98f6dafb4ceb8f3e79b05116a1e1?format=json, token=a1ae1713894f44a38f298df7815f6e5f, proxyPort=, proxy_host=null, host=16.77.19.30, object_port=8080, contentType=application/json, tenant=bd9b98f6dafb4ceb8f3e79b05116a1e1}}
2015-08-03 18:20:11:182 15506345 [1_WorkerExecutionThread-11_101600218] INFO  io.cloudslang.lang.cli.SlangCLI  - Event received: EVENT_ACTION_END Data is: {EXECUTION_ID=101600218, PATH=0, DESCRIPTION=Action performed, TIMESTAMP=Mon Aug 03 18:20:11 IST 2015, RETURN_VALUES={returnCode=0, responseHeaders=Content-Length: 17
Content-Type: text/plain
X-Trans-Id: txd6e0548cf8c34bbbaf5b5-0055bf63d3
Date: Mon, 03 Aug 2015 12:51:32 GMT
Connection: keep-alive, returnResult=An error occurred, reasonPhrase=Internal Error, finalLocation=http://16.77.19.30:8080/v1/AUTH_bd9b98f6dafb4ceb8f3e79b05116a1e1?format=json, protocolVersion=HTTP/1.1, statusCode=500}, STEP_TYPE=ACTION, STEP_NAME=null, TYPE=EVENT_ACTION_END}
2015-08-03 18:20:11:212 15506375 [1_WorkerExecutionThread-11_101600218] INFO  io.cloudslang.lang.cli.SlangCLI  - Event received: EVENT_OUTPUT_START Data is: {EXECUTION_ID=101600218, PATH=0, DESCRIPTION=Output binding started, executableResults=[io.cloudslang.lang.entities.bindings.Result@f7ad0e[name=SUCCESS,expression='statusCode' in locals() and statusCode == '200'], io.cloudslang.lang.entities.bindings.Result@619a66[name=FAILURE,expression=<null>]], TIMESTAMP=Mon Aug 03 18:20:11 IST 2015, executableOutputs=[io.cloudslang.lang.entities.bindings.Output@a19514[name=return_result,expression=returnResult], io.cloudslang.lang.entities.bindings.Output@1ab8b94[name=status_code,expression=statusCode], io.cloudslang.lang.entities.bindings.Output@b3dcf2[name=error_message,expression=returnResult if statusCode != '202' else '']], STEP_TYPE=EXECUTABLE, actionReturnValues=ReturnValues{result='null', outputs={returnCode=0, responseHeaders=Content-Length: 17
Content-Type: text/plain
X-Trans-Id: txd6e0548cf8c34bbbaf5b5-0055bf63d3
Date: Mon, 03 Aug 2015 12:51:32 GMT
Connection: keep-alive, returnResult=An error occurred, reasonPhrase=Internal Error, finalLocation=http://16.77.19.30:8080/v1/AUTH_bd9b98f6dafb4ceb8f3e79b05116a1e1?format=json, protocolVersion=HTTP/1.1, statusCode=500}}, STEP_NAME=get_openstack_containers, TYPE=EVENT_OUTPUT_START}
2015-08-03 18:20:11:222 15506385 [1_WorkerExecutionThread-11_101600218] INFO  io.cloudslang.lang.cli.SlangCLI  - Event received: EVENT_OUTPUT_END Data is: {EXECUTION_ID=101600218, PATH=0, DESCRIPTION=Output binding finished, TIMESTAMP=Mon Aug 03 18:20:11 IST 2015, STEP_TYPE=EXECUTABLE, STEP_NAME=get_openstack_containers, TYPE=EVENT_OUTPUT_END, RESULT=FAILURE, OUTPUTS={return_result=An error occurred, status_code=500, error_message=An error occurred}}
2015-08-03 18:20:11:222 15506385 [1_WorkerExecutionThread-11_101600218] INFO  io.cloudslang.lang.cli.SlangCLI  - Event received: EVENT_EXECUTION_FINISHED Data is: {EXECUTION_ID=101600218, PATH=0, DESCRIPTION=Execution finished running, TIMESTAMP=Mon Aug 03 18:20:11 IST 2015, STEP_TYPE=EXECUTABLE, STEP_NAME=get_openstack_containers, TYPE=EVENT_EXECUTION_FINISHED, RESULT=FAILURE, OUTPUTS={return_result=An error occurred, status_code=500, error_message=An error occurred}}
2015-08-03 18:20:11:252 15506415 [scoreWorkerScheduler-1] INFO  io.cloudslang.lang.cli.SlangCLI  - Event received: SCORE_FINISHED_EVENT Data is: {IS_BRANCH=false, executionIdContext=101600218, systemContext=io.cloudslang.score.lang.SystemContext@a326a6be, EXECUTION_CONTEXT={userInputs={}, runEnv=io.cloudslang.lang.runtime.env.RunEnvironment@1bd7806}}

**Comment by umavanth** [comment]
#   (c) Copyright 2014 Hewlett-Packard Development Company, L.P.
#   All rights reserved. This program and the accompanying materials
#   are made available under the terms of the Apache License v2.0 which accompany this distribution.
#
#   The Apache License is available at
#   http://www.apache.org/licenses/LICENSE-2.0
#
####################################################
# Performs a REST call to retrieve a list of OpenStack containers.
#
# Inputs:
#   - host - OpenStack machine host
#   - compute_port - optional - port used for OpenStack computations - Default: 8080
#   - token - OpenStack token obtained after authentication
#   - tenant - OpenStack tenantID obtained after authentication
#   - proxy_host - optional - proxy server used to access the web site - Default: none
#   - proxy_port - optional - proxy server port - Default: none
# Outputs:
#   - return_result - response of the operation
#   - status_code - normal statusCode is 202
#   - error_message - error message
# Results:
#   - SUCCESS - operation succeeded (statusCode == '200')
#   - FAILURE - otherwise
####################################################

namespace: io.cloudslang.openstack

operation:
  name: get_openstack_containers
  inputs:
    - host
    - object_port:
        default: "'8080'"
    - token
    - tenant
    - proxy_host:
        required: false
    - proxy_port:
        required: false
    - proxyHost: "proxy_host if proxy_host else ''"
    - proxyPort: "proxy_port if proxy_port else ''"
    - headers:
        default: "'X-AUTH-TOKEN:' + token"
        overridable: false
    - url:
        default: "'http://'+ host + ':' + object_port + '/v1/' + 'AUTH_' + tenant + '?format=json' "
        overridable: false
    - method:
        default: "'get'"
        overridable: false
    - contentType:
        default: "'application/json'"
        overridable: false

  action:
    java_action:
      className: io.cloudslang.content.httpclient.HttpClientAction
      methodName: execute
  outputs:
    - return_result: returnResult
    - status_code: statusCode
    - error_message: returnResult if statusCode != '202' else ''
  results:
    - SUCCESS : "'statusCode' in locals() and statusCode == '200'"
    - FAILURE

**Comment by meirwah** [comment]
Hi @umavanth , did it work in the end? or it still not working?

**Comment by oritstone** [comment]
@umavanth is it still an issue? or is it working already?

**Comment by umavanth** [comment]
Yes Orit, still I am facing the same issue

**Comment by mbettan** [comment]
Could you try this code ?
```
#   (c) Copyright 2014 Hewlett-Packard Development Company, L.P.
#   All rights reserved. This program and the accompanying materials
#   are made available under the terms of the Apache License v2.0 which accompany this distribution.
#
#   The Apache License is available at
#   http://www.apache.org/licenses/LICENSE-2.0
#
####################################################
# This flow performs an REST API call in order to poll a task in Nutanix PRISM
#
# Inputs:
#   - host - Nutanix host or IP Address endpoint
#   - username - required - the Nutanix username - Example: admin
#   - password - required - the Nutanix used for authentication
#   - proxy_host - optional - proxy server used to access the Nutanix host
#   - proxy_port - optional - proxy server port - Default: "'8080'"
#   - proxy_username - optional - user name used when connecting to the proxy
#   - proxy_password - optional - proxy server password associated with the <proxy_username> input value
#   - vmId - required - Id of the Virtual Machine to delete
# Outputs:
#   - return_result - the response of the operation in case of success, the error message otherwise
#   - error_message - return_result if statusCode is not "201"
#   - return_code - "0" if success, "-1" otherwise
#   - status_code - the code returned by the operation
####################################################

namespace: io.cloudslang.nutanix

imports:
  rest: io.cloudslang.base.network.rest

flow:
  name: get_openstack_containers
  inputs:
    - host
    - object_port:
        default: "'8080'"
    - token
    - tenant
    - proxy_host:
        required: false
    - proxy_port:
        default: "'8080'"
        required: false
    - proxy_username:
        required: false
    - proxy_password:
        required: false

  workflow:
    - delete_vm:
        do:
          rest.http_client_get:
            - url: "'http://'+ host + ':' + object_port + '/v1/' + 'AUTH_' + tenant + '?format=json'"
            - proxy_host:
                required: false
            - proxy_port:
                required: false
            - proxy_username:
                required: false
            - proxy_password:
                required: false
            - content_type: "'application/json'"
            - headers: "'X-AUTH-TOKEN:' + token"
        publish:
          - return_result
          - error_message
          - return_code
          - status_code

  outputs:
    - return_result
    - error_message
    - return_code
    - status_code

  results:
    - SUCCESS
    - FAILURE
```
