### ISSUE TITLE
Align content according to "Task arguments act like inputs" change

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang-content#330]
this will go in conjunction with issue CloudSlang/cloud-slang#288

**Comment by Bonczidai** [comment]
you can find more details about the change in CloudSlang/cloud-slang#288 .. now we support 2 syntaxes for task arguments:

`one-liner`
```yaml
    - get_containers_in_cluster:
        do:
          containers.get_filtered_containers: docker_options, all_containers = true, excluded_images = excluded
        publish:
          - container_ids
```

`standard-yaml`
```yaml
    - get_containers_in_cluster:
        do:
          containers.get_filtered_containers:
            - docker_options
            - all_containers: true
            - excluded_images: excluded
            - host: 'localhost'
            - port
            - username
            - password
            - private_key_file
            - character_set
            - pty
            - timeout: 300000
            - close_session
            - agent_forwarding
        publish:
          - container_ids
```

When we have lots of inputs `standard-yaml` is the obvious choice.. but we should decide on a convention on what syntax to use (in content written by us / doc) when having **few** inputs:

use `one-liner`:

```yaml
    - get_containers_in_cluster:
        do:
          containers.get_filtered_containers: >
                 docker_options, all_containers = true, excluded_images = excluded
        publish:
          - container_ids
```

 or `standard-yaml`:

```yaml
    - get_containers_in_cluster:
        do:
          containers.get_filtered_containers:
            - docker_options
            - all_containers: true
            - excluded_images: excluded
        publish:
          - container_ids
```

Please share your opinion - @meirwah @oritstone @SamMarkowitz  @tudorlesan @lirantal @mihaitusa @gituser173
