### ISSUE TITLE
Fix content according to the new expressions and string constants syntax [7]

### ISSUE THREAD

**Issue by oritstone** [CloudSlang/cloud-slang-content#410]

**Comment by Bonczidai** [comment]
some guidelines on the new syntax -- please check it:

```Yaml
# loaded by Yaml
- input_int: 22
- input_str_no_quotes: Hi
- input_str_single: 'Hi'
- input_str_double: "Hi"
- input_yaml_list: [1, 2, 3] # lists can also be loaded using expressions
- input_properties_yaml_map_folded: {default: medium, required: false} # this is not a map! rather `medium` as a str (maps can be loaded using expressions)

# evaluated via Python
- input_python_null:
    default: ${ None }
    required: false
- input_python_list: ${[1, 2, 3]} # lists can also be loaded using Yaml
- input_python_map: >
    ${{
    'key1': 'value1',
    'key2': 'value2',
    'key3': 'value3'
    }} # this is how you load a map - pay attention to indentation (we are still Yaml compatible)
- input_python_map_quotes: "${{'value': 2}}"
- b: b # str
- b_copy: ${ b }
- input_concat_1: ${'a' + b}
- input_concat_2_one_liner: ${'prefix_' + input_concat_1 + '_suffix'}
- input_concat_2_folded: > # you can break long expressions on multiple lines
    ${
    'prefix_' +
    input_concat_1 +
    '_suffix'
    }
```

@oritstone @maayan-avraham @SamMarkowitz @gituser173 @mihaitusa
