### ISSUE TITLE
python_action error

### ISSUE THREAD

**Issue by ww102111** [CloudSlang/cloud-slang-content#667]
Command failed java.lang.RuntimeException: java.lang.RuntimeException: Property: 'python_action' at: 'print' is illegal

**Comment by Bonczidai** [comment]
there is probably a misalignment between CLI and content version - starting with pre-release `v0.9.57` we changed the operation hierarchy - see [here](https://github.com/CloudSlang/cloud-slang/issues/675)

```
action:
  python_script: ..
->
python_action:
  script: ...
--------------------------------------------------------------------
action:
  java_action:
    className: com.hp.thing
    methodName: someMethod
->
java_action:
  class_name: com.hp.thing
  method_name: someMethod

```
