### ISSUE TITLE
Ping hosts navigation and inputs

### ISSUE THREAD

**Issue by SamMarkowitz** [CloudSlang/cloud-slang-content#75]
Navigation for up/down only takes into account the last iteration.

The following inputs should be `overridable: false`
- message_body: []
- all_nodes_are_up: True

**Comment by raskin-aleksandr** [comment]
Added `overridable: false` to input:
```
- message_body:
    default: []
    overridable: false
- all_nodes_are_up:
    default: True
    overridable: false
```
